# The URL the site will be built for
base_url = "https://trapdoorsec.com"
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "tabi"

title = "{TRAPDOOÐ¯ SECURITY}"

author = "seska"

generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]
taxonomies = [
    {name = "tags", feed = true },
]

[search]
index_format = "elasticlunr_json" # Or the less efficient "elasticlunr_javascript".
include_title = true
include_description = true
include_path = true
include_content = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
render_emoji = true
highlight_theme = "css"

[extra]
# Put all your custom variables here
stylesheets = ["/css/fontawesome.css", "/css/brands.css", "/css/solid.css"]
favicon = "/img/favicon.png"
show_remote_source = true
remote_repository_url = "https://github.com/seska451/blog"
menu  = [
    { name = "blog", url = "blog", trailing_slash = true },
    { name = "archive", url = "archive", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
    { name = "projects", url = "project", trailing_slash = true },
    { name = "walkthroughs", url = "walkthrough", trailing_slash = true }
]
email = "YWtzZXMwQHBtLm1lCg=="
